---
# tasks file for epel role
- when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
  block:
    - name: Install epel package on Amazon Linux
      ansible.builtin.command: amazon-linux-extras install epel -y
      args:
        creates: /etc/yum.repos.d/epel.repo
      when:
        - ansible_distribution == 'Amazon'
        - ansible_distribution_major_version == '2'
      tags: epel

    - name: Install epel package
      ansible.builtin.package:
        name: '{{ epel_package }}'
        state: present
        disable_gpg_check: true
        update_cache: true
      when: ansible_distribution != 'Amazon'
      tags: epel
