---
# defaults file for adguard role
# Common vars
adguardhome_home: /opt/AdGuardHome
adguardhome_version: latest
adguardhome_install_method: binary  # possible values binary, docker, snap
adguardhome_listen_all: true

# Binary relates vars
adguardhome_system_arch: amd64  # possible values 386, amd64, arm64,armv5, armv6, armv7
adguardhome_archive_name: 'AdGuardHome_linux_{{ adguardhome_system_arch }}.tar.gz'
adguardhome_bin_path: '{{ adguardhome_home }}/AdGuardHome'

# Docker related vars
adguardhome_docker_image: adguard/adguardhome
adguardhome_docker_hosts:
  - ['{{ ansible_fqdn }}', '{{ ansible_default_ipv4.address }}']
adguardhome_docker_labels: {}
adguardhome_docker_mounts:
  - '{{ adguardhome_home }}/conf:/opt/adguardhome/conf'
  - '{{ adguardhome_home }}/work:/opt/adguardhome/work'
adguardhome_docker_network: bridge
adguardhome_docker_ports:
  - 53:53/tcp
  - 53:53/udp
  - 3000:3000/tcp

# Snap related vars
adguardhome_snap_channel: latest/stable
