---
name: molecule

on:
  workflow_call:
    inputs:
      scenario:
        required: true
        type: string

env:
  WORK_DIR: ansible_collections/bonddim/linux

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Set build matrix
        id: set-matrix
        uses: bonddim/action-workflow-matrix@stable
        with:
          workflow: ${{ inputs.scenario }}

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: matrix
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.WORK_DIR }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: bonddim/action-lxd-init@stable
      - run: python -m pip install tox
      - name: 'Run tests with tox'
        run: |
          tox -e requirements
          tox -- test --scenario-name ${{ inputs.scenario }}
        working-directory: ${{ env.WORK_DIR }}
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          INSTALL_METHOD: ${{ matrix.install_method }}
